//! Grok Build **agent serve** process management for Settings → Runtime.
//!
//! CLI surface:
//! - `grok agent serve --bind <addr> --secret <token> [--remote <url>]`
//! - Default bind: `127.0.0.1:2419`
//! - Optional `--remote <URL>` enables serve **proxy mode** (upstream agent URL).
//! - Secret is auto-generated by the app and passed via `--secret` (never logged in full).
//!
//! Clients connect with:
//! - WebSocket URL: `ws://{bind}/ws?server-key={secret}`
//! - or CLI: `grok --remote ws://{bind}/ws --secret <token>`

use std::io::{Read, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::Path;
use std::process::Stdio;
use std::sync::Mutex;
use std::time::Duration;

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::cli_probe;
use crate::process_util;
use crate::store;

const SERVE_START_WAIT_MS: u64 = 4000;
const SERVE_START_POLL_MS: u64 = 150;
/// Default listen address for `grok agent serve` (matches CLI default).
pub const DEFAULT_SERVE_BIND: &str = "127.0.0.1:2419";
/// Unauthenticated HTTP path probed after `serve_start` (no secret, no query).
pub const UNAUTH_HEALTH_PATH: &str = "/health";
/// Connect / read / write timeout for the unauthenticated `/health` probe.
pub const UNAUTH_HEALTH_PROBE_MS: u64 = 800;

/// Classification of the first HTTP status line from an unauthenticated `/health` GET.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnauthHealthClass {
    Open,
    Closed,
    Inconclusive,
}

/// Whether `serve_start` may advertise connection strings and keep a non-loopback bind.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ServeAuthPolicy {
    pub advertise: bool,
    pub keep_bind: bool,
}

/// Tracked PID of a serve process **we** spawned.
static TRACKED_SERVE: Mutex<Option<TrackedServe>> = Mutex::new(None);

#[derive(Debug, Clone)]
struct TrackedServe {
    pid: u32,
    pgid: Option<i32>,
    bind: String,
    /// Full secret — kept only in process memory for stop/status masking.
    secret: String,
    /// Optional proxy-mode upstream URL (`--remote`); never contains the serve secret.
    remote: Option<String>,
}

/// Aggregate status for the Runtime panel (never includes the full secret).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServeStatusDto {
    /// `stopped` | `running` | `error` | `unsupported`
    pub state: String,
    /// Bind address we use / last used (default `127.0.0.1:2419`).
    pub bind: String,
    /// Optional proxy-mode upstream URL when this process was started with `--remote`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remote: Option<String>,
    /// Masked secret (`••••` + last 4) when we know it; never the full token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret_masked: Option<String>,
    /// Last 4 chars of secret when known (for compact UI).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret_last4: Option<String>,
    /// Full connection URL — **only** returned from `serve_start` once.
    /// Subsequent `serve_status` omits this so secrets do not linger in status polls.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection_url: Option<String>,
    /// Full client CLI string (`grok --remote ws://…/ws --secret …`) — **only** from `serve_start`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection_cli: Option<String>,
    /// Masked client CLI template for status polls (secret last-4 only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection_cli_masked: Option<String>,
    pub pid: Option<u64>,
    pub tracked_pid: Option<u64>,
    /// True when TCP connect to bind succeeds (best-effort). Does **not** probe `--remote` upstream.
    pub port_open: bool,
    pub cli_found: bool,
    pub cli_supports_serve: bool,
    /// True when `grok agent serve --help` exposes `--remote` (proxy mode).
    #[serde(default)]
    pub cli_supports_remote: bool,
    /// True when listening on a non-loopback bind address.
    #[serde(default)]
    pub non_loopback: bool,
    /// Security notice/warning when listening on a non-loopback bind address.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exposure_warning: Option<String>,
    pub message: Option<String>,
}

// ── Pure helpers (unit-tested) ──────────────────────────────────────────────

/// Mask secrets for UI / logs (never show full serve secret).
/// Same policy as leader: short values → all bullets; longer → bullets + last 4.
pub fn mask_secret(value: &str) -> String {
    let t = value.trim();
    if t.is_empty() {
        return String::new();
    }
    if t.len() <= 4 {
        return "••••".into();
    }
    let visible = t
        .chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect::<String>();
    format!("••••{visible}")
}

/// Last 4 characters of a secret (or empty / full if shorter).
pub fn secret_last4(value: &str) -> String {
    let t = value.trim();
    if t.is_empty() {
        return String::new();
    }
    t.chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect()
}

/// Cryptographic random secret (≥32 bytes, URL-safe base64, no padding).
pub fn generate_serve_secret() -> String {
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}

/// Normalize / validate a bind string (`host:port`). Empty → default.
pub fn normalize_bind(bind: Option<&str>) -> Result<String, String> {
    let raw = bind
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or(DEFAULT_SERVE_BIND);
    // Reject whitespace and scheme prefixes so we only accept host:port.
    if raw.contains("://") || raw.contains('/') || raw.contains(' ') {
        return Err(format!("invalid serve bind (expected host:port): {raw}"));
    }
    // Must resolve to at least one socket addr.
    let addrs: Vec<SocketAddr> = raw
        .to_socket_addrs()
        .map_err(|e| format!("invalid serve bind `{raw}`: {e}"))?
        .collect();
    if addrs.is_empty() {
        return Err(format!("invalid serve bind `{raw}`: no addresses"));
    }
    if addrs.iter().any(|a| !a.ip().is_loopback()) {
        tracing::warn!(
            target: "grok_app::serve",
            bind = %raw,
            "Serve bind address is non-loopback ({raw}); WebSocket port is exposed to the local network or internet"
        );
    }
    Ok(raw.to_string())
}

/// Check if a bind string resolves to any non-loopback addresses.
pub fn is_non_loopback_bind(bind: &str) -> bool {
    if let Ok(addrs) = bind.to_socket_addrs() {
        addrs.into_iter().any(|a| !a.ip().is_loopback())
    } else {
        false
    }
}

fn split_bind_host_port(bind: &str) -> (&str, Option<&str>) {
    let bind = bind.trim();
    if bind.starts_with('[') {
        if let Some(close) = bind.find(']') {
            let host = &bind[..=close];
            let after = &bind[close + 1..];
            let port = after.strip_prefix(':').filter(|p| !p.is_empty());
            return (host, port);
        }
    }
    match bind.rsplit_once(':') {
        Some((host, port)) if !host.is_empty() && !port.is_empty() => (host, Some(port)),
        _ => (bind, None),
    }
}

fn rewrite_unauth_health_host(host: &str) -> String {
    match host {
        "0.0.0.0" => "127.0.0.1".to_string(),
        "::" | "[::]" => "[::1]".to_string(),
        other => other.to_string(),
    }
}

fn rewrite_unauth_health_bind(bind: &str) -> String {
    let (host, port) = split_bind_host_port(bind);
    let host = rewrite_unauth_health_host(host);
    match port {
        Some(port) => format!("{host}:{port}"),
        None => host,
    }
}

/// `http://{rewritten-host:port}/health` — path already includes the slash.
pub fn unauth_health_url(bind: &str) -> String {
    format!(
        "http://{}{}",
        rewrite_unauth_health_bind(bind),
        UNAUTH_HEALTH_PATH
    )
}

pub fn classify_unauth_health_status(status: Option<u16>) -> UnauthHealthClass {
    match status {
        Some(200..=299) => UnauthHealthClass::Open,
        Some(_) => UnauthHealthClass::Closed,
        None => UnauthHealthClass::Inconclusive,
    }
}

pub fn serve_auth_policy(class: UnauthHealthClass, non_loopback: bool) -> ServeAuthPolicy {
    ServeAuthPolicy {
        advertise: class != UnauthHealthClass::Open,
        keep_bind: !(non_loopback && class == UnauthHealthClass::Open),
    }
}

/// Client-facing WebSocket base (no secret): `ws://{bind}/ws`.
pub fn build_remote_ws_base(bind: &str) -> String {
    format!("ws://{bind}/ws")
}

/// Build the WebSocket connection URL clients use (`ws://{bind}/ws?server-key=…`).
pub fn build_connection_url(bind: &str, secret: &str) -> String {
    // Bind is host:port (possibly IPv6 in brackets already, or bare host:port).
    format!("ws://{bind}/ws?server-key={secret}")
}

/// Build a log-safe connection URL with masked secret query value.
pub fn build_connection_url_masked(bind: &str, secret: &str) -> String {
    format!("ws://{bind}/ws?server-key={}", mask_secret(secret))
}

/// Client CLI connection guidance avoiding plaintext secret exposure on argv:
/// `GROK_SERVE_SECRET=<secret> grok --remote ws://{bind}/ws`.
pub fn build_connection_cli(bind: &str, secret: &str) -> String {
    format!(
        "GROK_SERVE_SECRET={} grok --remote {}",
        secret,
        build_remote_ws_base(bind)
    )
}

/// Log/UI-safe CLI connection string with masked secret.
pub fn build_connection_cli_masked(bind: &str, secret: &str) -> String {
    format!(
        "GROK_SERVE_SECRET={} grok --remote {}",
        mask_secret(secret),
        build_remote_ws_base(bind)
    )
}

/// Normalize optional proxy-mode `--remote` URL. Empty → `None`.
///
/// Accepts `ws://` / `wss://` (optionally `http(s)://` rewritten to ws/wss).
/// Rejects secrets in the query (`server-key`, `secret`, `token`, …) so the
/// upstream URL never carries the local serve token, and rejects junk/whitespace.
pub fn normalize_remote_url(remote: Option<&str>) -> Result<Option<String>, String> {
    let raw = match remote.map(str::trim).filter(|s| !s.is_empty()) {
        Some(s) => s,
        None => return Ok(None),
    };
    if raw.contains(char::is_whitespace) {
        return Err("invalid serve --remote URL (whitespace not allowed)".into());
    }
    if raw.contains('\0') {
        return Err("invalid serve --remote URL".into());
    }

    let lower = raw.to_ascii_lowercase();
    let normalized = if lower.starts_with("ws://") || lower.starts_with("wss://") {
        raw.to_string()
    } else if lower.starts_with("http://") {
        format!("ws://{}", &raw["http://".len()..])
    } else if lower.starts_with("https://") {
        format!("wss://{}", &raw["https://".len()..])
    } else {
        return Err(format!(
            "invalid serve --remote URL (expected ws:// or wss://): {raw}"
        ));
    };

    // Reject credential-bearing query / fragment that look like secrets.
    if let Some(q_start) = normalized.find('?') {
        let q = normalized[q_start + 1..].to_ascii_lowercase();
        for key in [
            "server-key",
            "secret",
            "token",
            "password",
            "api_key",
            "apikey",
        ] {
            if q.contains(&format!("{key}=")) || q.starts_with(&format!("{key}=")) {
                return Err(
                    "invalid serve --remote URL: do not include secrets in the URL query".into(),
                );
            }
        }
    }

    // Must have a host after the scheme.
    let after_scheme = normalized
        .split_once("://")
        .map(|(_, rest)| rest)
        .unwrap_or("");
    let host_part = after_scheme.split(['/', '?', '#']).next().unwrap_or("");
    if host_part.is_empty() {
        return Err(format!("invalid serve --remote URL (empty host): {raw}"));
    }

    Ok(Some(normalized))
}

/// Detect serve support from `grok agent serve --help` combined stdout/stderr.
pub fn parse_serve_help_supports(stdout: &str, stderr: &str, ok: bool) -> bool {
    if !ok {
        return false;
    }
    let blob = format!("{stdout}\n{stderr}").to_ascii_lowercase();
    // Fail closed: require both bind and secret surface.
    (blob.contains("--bind") || blob.contains("bind"))
        && (blob.contains("--secret") || blob.contains("secret"))
        && (blob.contains("websocket") || blob.contains("serve") || blob.contains("listen"))
}

/// Whether help text advertises proxy-mode `--remote`.
pub fn parse_serve_help_supports_remote(stdout: &str, stderr: &str, ok: bool) -> bool {
    if !ok {
        return false;
    }
    let blob = format!("{stdout}\n{stderr}").to_ascii_lowercase();
    blob.contains("--remote")
}

/// Derive panel state from CLI capability + tracked process + port probe.
pub fn derive_serve_state(
    cli_found: bool,
    cli_supports_serve: bool,
    tracked_alive: bool,
    port_open: bool,
    support_msg: Option<&str>,
) -> (&'static str, Option<String>) {
    if !cli_found {
        return (
            "error",
            Some("Grok Build CLI not found. Install or set the CLI path under Runtime.".into()),
        );
    }
    if !cli_supports_serve {
        return (
            "unsupported",
            Some(
                support_msg
                    .unwrap_or(
                        "This Grok Build CLI version does not expose `agent serve` (WebSocket server).",
                    )
                    .to_string(),
            ),
        );
    }
    if tracked_alive || port_open {
        return ("running", None);
    }
    ("stopped", None)
}

// ── Process / CLI helpers ───────────────────────────────────────────────────

fn run_grok_cli_args(args: &[&str], timeout_secs: u64) -> Result<(String, String, bool), String> {
    let settings = store::load_settings();
    let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
    let Some(cli_path) = probe.path.filter(|_| probe.found) else {
        return Err("Grok Build CLI not found".into());
    };

    let args_owned: Vec<String> = args.iter().map(|s| (*s).to_string()).collect();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let mut cmd = std::process::Command::new(&cli_path);
        cmd.args(&args_owned);
        process_util::apply_cli_env_std(&mut cmd);
        let result = cmd.output();
        let _ = tx.send(result);
    });

    match rx.recv_timeout(Duration::from_secs(timeout_secs)) {
        Ok(Ok(output)) => {
            let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            Ok((stdout, stderr, output.status.success()))
        }
        Ok(Err(e)) => Err(format!("Failed to run grok: {e}")),
        Err(_) => Err(format!("grok command timed out after {timeout_secs}s")),
    }
}

/// (cli_found, cli_supports_serve, cli_supports_remote, support_msg)
fn probe_cli_supports_serve() -> (bool, bool, bool, Option<String>) {
    let settings = store::load_settings();
    let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
    if !probe.found {
        return (false, false, false, Some("Grok Build CLI not found".into()));
    }
    match run_grok_cli_args(&["agent", "serve", "--help"], 8) {
        Ok((stdout, stderr, ok)) => {
            let supports = parse_serve_help_supports(&stdout, &stderr, ok);
            let supports_remote = parse_serve_help_supports_remote(&stdout, &stderr, ok);
            if supports {
                (true, true, supports_remote, None)
            } else {
                (
                    true,
                    false,
                    false,
                    Some(
                        "This Grok Build CLI version does not expose `agent serve` (WebSocket server)."
                            .into(),
                    ),
                )
            }
        }
        Err(e) => {
            if e.contains("not found") {
                (false, false, false, Some(e))
            } else {
                (true, false, false, Some(e))
            }
        }
    }
}

fn pid_alive(pid: u32) -> bool {
    #[cfg(unix)]
    {
        libc_kill(pid as i32, 0) == 0
    }
    #[cfg(windows)]
    {
        let out = process_util::command("tasklist")
            .args(["/FI", &format!("PID eq {pid}"), "/NH"])
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .output();
        match out {
            Ok(o) => {
                let s = String::from_utf8_lossy(&o.stdout);
                s.contains(&pid.to_string())
            }
            Err(_) => false,
        }
    }
}

fn kill_tracked(pid: u32, pgid: Option<i32>) {
    #[cfg(unix)]
    {
        if let Some(g) = pgid.or(Some(pid as i32)) {
            let _ = libc_kill(-g, 15); // SIGTERM group
            std::thread::sleep(Duration::from_millis(200));
            let _ = libc_kill(-g, 9);
            let _ = libc_waitpid(pid as i32);
        }
    }
    #[cfg(windows)]
    {
        let _ = pgid;
        let _ = process_util::command("taskkill")
            .args(["/PID", &pid.to_string(), "/T", "/F"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

#[cfg(unix)]
fn libc_kill(pid: i32, sig: i32) -> i32 {
    extern "C" {
        fn kill(pid: i32, sig: i32) -> i32;
    }
    unsafe { kill(pid, sig) }
}

#[cfg(unix)]
fn libc_setsid() -> i32 {
    extern "C" {
        fn setsid() -> i32;
    }
    unsafe { setsid() }
}

#[cfg(unix)]
fn libc_waitpid(pid: i32) -> i32 {
    extern "C" {
        fn waitpid(pid: i32, status: *mut i32, options: i32) -> i32;
    }
    // WNOHANG = 1
    unsafe { waitpid(pid, std::ptr::null_mut(), 1) }
}

fn clear_tracked_if_dead() {
    let mut guard = match TRACKED_SERVE.lock() {
        Ok(g) => g,
        Err(_) => return,
    };
    if let Some(t) = guard.as_ref() {
        if !pid_alive(t.pid) {
            *guard = None;
        }
    }
}

/// Best-effort TCP connect to bind (short timeout).
pub fn port_is_open(bind: &str) -> bool {
    let Ok(mut addrs) = bind.to_socket_addrs() else {
        return false;
    };
    let Some(addr) = addrs.next() else {
        return false;
    };
    TcpStream::connect_timeout(&addr, Duration::from_millis(200)).is_ok()
}

fn parse_unauth_health_status_line(buf: &[u8]) -> Option<u16> {
    let text = std::str::from_utf8(buf).ok()?;
    let line = text.lines().next()?;
    let mut parts = line.split_whitespace();
    let version = parts.next()?;
    if !version.starts_with("HTTP/1.") {
        return None;
    }
    parts.next()?.parse().ok()
}

fn probe_unauth_health(bind: &str) -> UnauthHealthClass {
    let url = unauth_health_url(bind);
    let hostport = match url.strip_prefix("http://") {
        Some(rest) => {
            let hostport = rest.split('/').next().unwrap_or("");
            if hostport.is_empty() {
                return classify_unauth_health_status(None);
            }
            hostport.to_string()
        }
        None => return classify_unauth_health_status(None),
    };

    let timeout = Duration::from_millis(UNAUTH_HEALTH_PROBE_MS);
    let Ok(mut addrs) = hostport.to_socket_addrs() else {
        return classify_unauth_health_status(None);
    };
    let Some(addr) = addrs.next() else {
        return classify_unauth_health_status(None);
    };
    let mut stream = match TcpStream::connect_timeout(&addr, timeout) {
        Ok(s) => s,
        Err(_) => return classify_unauth_health_status(None),
    };
    if stream.set_write_timeout(Some(timeout)).is_err()
        || stream.set_read_timeout(Some(timeout)).is_err()
    {
        return classify_unauth_health_status(None);
    }

    let host = split_bind_host_port(&hostport).0;
    let request =
        format!("GET {UNAUTH_HEALTH_PATH} HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\n\r\n");
    if stream.write_all(request.as_bytes()).is_err() {
        return classify_unauth_health_status(None);
    }

    let mut buf = [0u8; 8192];
    match stream.read(&mut buf) {
        Ok(0) => classify_unauth_health_status(None),
        Ok(n) => classify_unauth_health_status(parse_unauth_health_status_line(&buf[..n])),
        Err(_) => classify_unauth_health_status(None),
    }
}

pub fn build_serve_command(
    cli_path: &Path,
    bind: &str,
    secret: &str,
    remote: Option<&str>,
) -> std::process::Command {
    let mut cmd = std::process::Command::new(cli_path);
    cmd.arg("agent").arg("serve").arg("--bind").arg(bind);
    if let Some(r) = remote {
        cmd.arg("--remote").arg(r);
    }
    cmd.stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());

    process_util::apply_no_window_std(&mut cmd);
    process_util::ensure_home_env_std(&mut cmd);
    if let Some(path_env) = process_util::enriched_path_env() {
        cmd.env("PATH", path_env);
    }
    // `--remote` upstream may need the app proxy (NEW-02).
    crate::proxy::apply_to_std_command(&mut cmd);
    // Pass secret via environment variable GROK_SERVE_SECRET to avoid command-line secret leaks on argv.
    cmd.env("GROK_SERVE_SECRET", secret);
    cmd.env("GROK_AGENT_SECRET", secret);

    cmd
}

fn spawn_serve_process(
    cli_path: &Path,
    bind: &str,
    secret: &str,
    remote: Option<&str>,
) -> Result<TrackedServe, String> {
    // Never log full secret — only bind + masked secret + optional remote (no secret).
    tracing::info!(
        target: "grok_app::serve",
        bind = %bind,
        secret = %mask_secret(secret),
        remote = remote.unwrap_or(""),
        "spawning grok agent serve"
    );

    let mut cmd = build_serve_command(cli_path, bind, secret, remote);

    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        // SAFETY: runs in child before exec; setsid → new session = process group.
        unsafe {
            cmd.pre_exec(|| {
                if libc_setsid() == -1 {
                    return Err(std::io::Error::last_os_error());
                }
                Ok(())
            });
        }
    }
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        cmd.creation_flags(CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW);
    }

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("failed to spawn grok agent serve: {e}"))?;
    let pid = child.id();
    // Reap in background so we never leave zombies.
    std::thread::spawn(move || {
        let _ = child.wait();
    });

    Ok(TrackedServe {
        pid,
        pgid: Some(pid as i32),
        bind: bind.to_string(),
        secret: secret.to_string(),
        remote: remote.map(|s| s.to_string()),
    })
}

fn collect_status_sync(include_connection_secrets: bool) -> ServeStatusDto {
    clear_tracked_if_dead();

    let (cli_found, cli_supports_serve, cli_supports_remote, support_msg) =
        probe_cli_supports_serve();

    let tracked = TRACKED_SERVE.lock().ok().and_then(|g| g.clone());
    let tracked_alive = tracked.as_ref().map(|t| pid_alive(t.pid)).unwrap_or(false);
    let bind = tracked
        .as_ref()
        .map(|t| t.bind.clone())
        .unwrap_or_else(|| DEFAULT_SERVE_BIND.to_string());
    let remote = tracked.as_ref().and_then(|t| t.remote.clone());
    let port_open = if cli_found && cli_supports_serve {
        port_is_open(&bind)
    } else {
        false
    };

    let (state, mut message) = derive_serve_state(
        cli_found,
        cli_supports_serve,
        tracked_alive,
        port_open,
        support_msg.as_deref(),
    );
    if message.is_none() {
        message = support_msg;
    }

    let (secret_masked, secret_last4_v, connection_url, connection_cli, connection_cli_masked) =
        if let Some(ref t) = tracked {
            let masked = mask_secret(&t.secret);
            let last4 = secret_last4(&t.secret);
            let cli_masked = build_connection_cli_masked(&t.bind, &t.secret);
            let (url, cli) = if include_connection_secrets {
                (
                    Some(build_connection_url(&t.bind, &t.secret)),
                    Some(build_connection_cli(&t.bind, &t.secret)),
                )
            } else {
                (None, None)
            };
            (Some(masked), Some(last4), url, cli, Some(cli_masked))
        } else {
            (None, None, None, None, None)
        };

    // If port is open but we did not spawn serve, surface honest partial status.
    if state == "running" && tracked.is_none() && port_open {
        message = Some(format!(
            "Port {bind} is open (external serve or other process). Start/stop only manages processes started from this app."
        ));
    } else if state == "running" && remote.is_some() && message.is_none() {
        // Honest health note: TCP probe only covers bind, not proxy upstream.
        message = Some(
            "Health check probes local bind TCP only; optional --remote upstream is not probed."
                .into(),
        );
    }

    let non_loopback = is_non_loopback_bind(&bind);
    let exposure_warning = if non_loopback {
        Some(format!(
            "Security notice: serve is listening on non-loopback bind `{bind}` and exposed to the network."
        ))
    } else {
        None
    };
    if non_loopback && message.is_none() {
        message = exposure_warning.clone();
    }

    ServeStatusDto {
        state: state.into(),
        bind,
        remote,
        secret_masked,
        secret_last4: secret_last4_v,
        connection_url,
        connection_cli,
        connection_cli_masked,
        pid: tracked.as_ref().map(|t| t.pid as u64),
        tracked_pid: tracked.as_ref().map(|t| t.pid as u64),
        port_open,
        cli_found,
        cli_supports_serve,
        cli_supports_remote,
        non_loopback,
        exposure_warning,
        message,
    }
}

fn finish_serve_start_with_probe(bind: &str) -> Result<ServeStatusDto, String> {
    let class = probe_unauth_health(bind);
    let policy = serve_auth_policy(class, is_non_loopback_bind(bind));
    if !policy.keep_bind {
        if let Ok(mut guard) = TRACKED_SERVE.lock() {
            if let Some(t) = guard.take() {
                tracing::info!(
                    target: "grok_app::serve",
                    pid = t.pid,
                    bind = %t.bind,
                    secret = %mask_secret(&t.secret),
                    "stopping agent serve"
                );
                if pid_alive(t.pid) {
                    kill_tracked(t.pid, t.pgid);
                }
            }
        }
        return Err(format!(
            "Refusing unauthenticated serve on non-loopback bind `{bind}`"
        ));
    }
    let mut st = if policy.advertise {
        collect_status_sync(true)
    } else {
        collect_status_sync(false)
    };
    if class == UnauthHealthClass::Open {
        st.connection_url = None;
        st.connection_cli = None;
        st.message = Some(format!(
            "Unauthenticated HTTP GET /health succeeded on `{bind}`"
        ));
    }
    Ok(st)
}

// ── Tauri commands ──────────────────────────────────────────────────────────

/// Status for Settings → Runtime → Agent serve (secret always masked).
#[tauri::command]
pub async fn serve_status() -> Result<ServeStatusDto, String> {
    tauri::async_runtime::spawn_blocking(|| collect_status_sync(false))
        .await
        .map_err(|e| e.to_string())
}

/// Start `grok agent serve --bind --secret [--remote]` (auto secret; default bind).
/// Returns status **including** one-time full `connectionUrl` / `connectionCli` for copy.
#[tauri::command]
pub async fn serve_start(
    window: tauri::Window,
    bind: Option<String>,
    remote: Option<String>,
) -> Result<ServeStatusDto, String> {
    let caller = window.label().to_string();
    crate::commands::require_main_window_label(&caller)?;
    tauri::async_runtime::spawn_blocking(move || {
        let current = collect_status_sync(false);
        if current.state == "running" && current.tracked_pid.is_some() {
            // Already our process — re-issue connection URL / CLI for copy.
            let probe_bind = if current.bind.is_empty() {
                DEFAULT_SERVE_BIND
            } else {
                current.bind.as_str()
            };
            return finish_serve_start_with_probe(probe_bind);
        }
        if !current.cli_found {
            return Err("Grok Build CLI not found".into());
        }
        if !current.cli_supports_serve {
            return Err(current.message.unwrap_or_else(|| {
                "This CLI version cannot run `grok agent serve`".into()
            }));
        }

        // External process already on the default/requested port — fail closed rather
        // than double-bind and leak a secret for a process we do not control.
        let bind_norm = normalize_bind(bind.as_deref())?;
        if is_non_loopback_bind(&bind_norm) {
            tracing::warn!(
                target: "grok_app::serve",
                bind = %bind_norm,
                "Starting grok agent serve on non-loopback bind `{bind_norm}`; WebSocket server is exposed to local network/internet"
            );
        }
        let remote_norm = normalize_remote_url(remote.as_deref())?;
        if remote_norm.is_some() && !current.cli_supports_remote {
            return Err(
                "This Grok Build CLI version does not support `agent serve --remote` (proxy mode)."
                    .into(),
            );
        }
        if port_is_open(&bind_norm) && current.tracked_pid.is_none() {
            return Err(format!(
                "Port {bind_norm} is already in use. Stop the existing process or choose another bind."
            ));
        }

        let settings = store::load_settings();
        let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
        let Some(cli_path) = probe.path.filter(|_| probe.found) else {
            return Err("Grok Build CLI not found".into());
        };

        let secret = generate_serve_secret();
        // Log only masked secret + remote (remote has no secret by validation).
        tracing::info!(
            target: "grok_app::serve",
            bind = %bind_norm,
            secret = %mask_secret(&secret),
            remote = remote_norm.as_deref().unwrap_or(""),
            url = %build_connection_url_masked(&bind_norm, &secret),
            cli = %build_connection_cli_masked(&bind_norm, &secret),
            "starting agent serve"
        );

        let tracked = spawn_serve_process(
            Path::new(&cli_path),
            &bind_norm,
            &secret,
            remote_norm.as_deref(),
        )?;
        {
            let mut guard = TRACKED_SERVE
                .lock()
                .map_err(|_| "serve tracker lock poisoned".to_string())?;
            *guard = Some(tracked);
        }

        let deadline = std::time::Instant::now() + Duration::from_millis(SERVE_START_WAIT_MS);
        loop {
            if let Ok(g) = TRACKED_SERVE.lock() {
                if let Some(t) = g.as_ref() {
                    if !pid_alive(t.pid) {
                        drop(g);
                        let mut g2 = TRACKED_SERVE.lock().ok();
                        if let Some(ref mut gg) = g2 {
                            **gg = None;
                        }
                        return Err(
                            "Serve process exited immediately after start. Check CLI auth / logs."
                                .into(),
                        );
                    }
                }
            }
            if port_is_open(&bind_norm) {
                return finish_serve_start_with_probe(&bind_norm);
            }
            if std::time::Instant::now() >= deadline {
                return finish_serve_start_with_probe(&bind_norm);
            }
            std::thread::sleep(Duration::from_millis(SERVE_START_POLL_MS));
        }
    })
    .await
    .map_err(|e| e.to_string())?
}

/// Stop the tracked `grok agent serve` process (app-spawned only).
#[tauri::command]
pub async fn serve_stop() -> Result<ServeStatusDto, String> {
    tauri::async_runtime::spawn_blocking(|| {
        if let Ok(mut guard) = TRACKED_SERVE.lock() {
            if let Some(t) = guard.take() {
                tracing::info!(
                    target: "grok_app::serve",
                    pid = t.pid,
                    bind = %t.bind,
                    secret = %mask_secret(&t.secret),
                    "stopping agent serve"
                );
                if pid_alive(t.pid) {
                    kill_tracked(t.pid, t.pgid);
                }
            }
        }
        // Brief settle so port probe reflects closed.
        std::thread::sleep(Duration::from_millis(150));
        Ok(collect_status_sync(false))
    })
    .await
    .map_err(|e| e.to_string())?
}

/// TCP health probe result (latency only — no secrets, no WebSocket handshake).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServeTcpProbeResult {
    pub ok: bool,
    pub latency_ms: Option<u64>,
    pub error: Option<String>,
    /// Bare `host:port` that was probed (never includes query/secret).
    pub target: String,
}

/// Normalize a probe address to bare `host:port`.
/// Rejects schemes, paths, query strings (so secrets never reach the probe path).
pub fn normalize_probe_addr(raw: &str) -> Result<String, String> {
    let s = raw.trim();
    if s.is_empty() {
        return Err("empty address".into());
    }
    // Fail closed on anything that might carry a secret or non-TCP target.
    if s.contains("://") || s.contains('/') || s.contains('?') || s.contains('#') {
        return Err("probe address must be host:port only (no URL scheme, path, or query)".into());
    }
    if s.to_ascii_lowercase().contains("server-key") || s.to_ascii_lowercase().contains("secret=") {
        return Err("probe address must not include a secret".into());
    }
    if s.contains(' ') {
        return Err("invalid probe address".into());
    }
    // Must resolve.
    let addrs: Vec<SocketAddr> = s
        .to_socket_addrs()
        .map_err(|e| format!("invalid probe address `{s}`: {e}"))?
        .collect();
    if addrs.is_empty() {
        return Err(format!("invalid probe address `{s}`: no addresses"));
    }
    Ok(s.to_string())
}

/// TCP connect to `host:port` with a ~2s timeout. Network path only — no
/// WebSocket upgrade, no auth. Used by the SDK Connect wizard health check.
/// Callers must pass bare host:port (frontend strips secrets from pasted URLs).
#[tauri::command]
pub async fn serve_tcp_probe(addr: String) -> Result<ServeTcpProbeResult, String> {
    let target = match normalize_probe_addr(&addr) {
        Ok(t) => t,
        Err(e) => {
            return Ok(ServeTcpProbeResult {
                ok: false,
                latency_ms: None,
                error: Some(e),
                target: addr.trim().to_string(),
            });
        }
    };

    // Log only the bare target — never a URL with credentials.
    tracing::debug!(
        target: "grok_app::serve",
        target = %target,
        "tcp probe"
    );

    let target_for_thread = target.clone();
    let result = tauri::async_runtime::spawn_blocking(move || {
        let started = std::time::Instant::now();
        let Ok(mut addrs) = target_for_thread.to_socket_addrs() else {
            return ServeTcpProbeResult {
                ok: false,
                latency_ms: None,
                error: Some(format!("could not resolve {target_for_thread}")),
                target: target_for_thread,
            };
        };
        let Some(sock) = addrs.next() else {
            return ServeTcpProbeResult {
                ok: false,
                latency_ms: None,
                error: Some(format!("no addresses for {target_for_thread}")),
                target: target_for_thread,
            };
        };
        match TcpStream::connect_timeout(&sock, Duration::from_secs(2)) {
            Ok(_stream) => ServeTcpProbeResult {
                ok: true,
                latency_ms: Some(started.elapsed().as_millis() as u64),
                error: None,
                target: target_for_thread,
            },
            Err(e) => ServeTcpProbeResult {
                ok: false,
                latency_ms: Some(started.elapsed().as_millis() as u64),
                error: Some(e.to_string()),
                target: target_for_thread,
            },
        }
    })
    .await
    .map_err(|e| e.to_string())?;

    Ok(result)
}

include!("serve_tests_ext.rs");
